---
- name: Store fixpack name
  ansible.builtin.set_fact:
    fixpack_tar: '{{ mq_local_path | basename }}'

- name: Store fixpack directory
  ansible.builtin.set_fact:
    fixpack_dir: '{{ fixpack_tar | replace(".tar.gz","") }}'

- name: Copy fixpack to target
  ansible.builtin.copy:
    src: '{{ mq_local_path }}'
    dest: '/var'
    mode: "0644"

- name: Create fixpack directory
  ansible.builtin.file:
    path: '/var/{{ fixpack_dir }}'
    state: directory

- name: Extract fixpack fom zip
  ansible.builtin.unarchive:
    src: '/var/{{ fixpack_tar }}'
    remote_src: true
    dest: '/var/{{ fixpack_dir }}'

- name: Check if MQ license has been accepted
  ansible.builtin.stat:
    path: '/var/MQServer/licensestatus.txt'
  register: license_status

- name: Accept MQ license if not already done
  ansible.builtin.shell: >-
    /var/MQServer/mqlicense.sh
    -{{ ibmMqLicence }} >
    /var/MQServer/licensestatus.txt
  changed_when: not license_status.stat.exists

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: End web server
  become_user: mqm
  ansible.builtin.command: endmqweb
  register: mqweb_status
  failed_when: mqweb_status.stderr != ""

- name: Find required package files
  ansible.builtin.find:
    paths: '/var/{{ fixpack_dir }}'
    use_regex: true
    patterns: '{{ item }}'
  register: package_files
  with_items:
    - (?i).*runtime.*
    - (?i).*gskit.*
    - (?i).*server.*
    - (?i).*java.*
    - (?i).*jre.*
    - (?i).*sdk.*
    - (?i).*samples.*
    - (?i).*man.*
    - (?i).*client.*
    - (?i).*amqp.*
    - (?i).*ams.*
    - (?i).*web.*
    - (?i).*(-|_)es.*
    - (?i).*(-|_)cn.*
    # - '(?i).*ftbase.*'
    # - '(?i).*ftlogger.*'
    # - '(?i).*fttools.*'
    # - '(?i).*ftagent.*'
    # - '(?i).*ftservice.*'
    # - '(?i).*xrservice.*'
    # - '(?i).*sfbridge.*'
    # - '(?i).*bcbridge.*'
    # - '(?i).*(-|_)de.*'
    # - '(?i).*(-|_)fr.*'
    # - '(?i).*(-|_)ja.*'
    # - '(?i).*(-|_)it.*'
    # - '(?i).*(-|_)ko.*'
    # - '(?i).*(-|_)ru.*'
    # - '(?i).*(-|_)pt.*'
    # - '(?i).*(-|_)hu.*'
    # - '(?i).*(-|_)pl.*'
    # - '(?i).*(-|_)cs.*'
    # - '(?i).*(-|_)tw.*'
  when: '"MQSeriesRuntime" in ansible_facts.packages or "ibmmq-runtime" in ansible_facts.packages'

- name: Create a list of paths to the packages from found files
  ansible.builtin.set_fact:
    package_list: "{{ package_files.results | map(attribute='files.0.path') | list }}"
  when: '"MQSeriesRuntime" in ansible_facts.packages or "ibmmq-runtime" in ansible_facts.packages'

- name: Deb Installation
  ansible.builtin.apt:
    deb: '{{ item }}'
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - "'ibmmq-runtime' in ansible_facts.packages"
  loop: '{{ package_list }}'

- name: RPM Installation
  ansible.builtin.dnf:
    name: "{{ package_list }}"
    state: present
    disable_gpg_check: true
  when:
    - ansible_distribution == 'RedHat'
    - "'MQSeriesRuntime' in ansible_facts.packages"

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection