---

- name: Check if license status file exists
  stat:
    path: /var/MQServer/licensestatus.txt
  register: license_status

- name: Accept MQ license
  shell: |
    /var/MQServer/mqlicense.sh -{{ ibmMqLicence}} > /var/MQServer/licensestatus.txt
  changed_when: not license_status.stat.exists

- name: Install python3-rpm (SLES)
  shell: zypper install python3-rpm
  when: ansible_distribution == 'SLES'

- name: Gather package facts
  package_facts:
    manager: auto

- name: Find required package files
  find:
    paths: "/var/MQServer"
    use_regex: yes
    patterns: "{{ item }}"
  register: package_files
  with_items: 
    - '(?i).*runtime.*'
    - '(?i).*server.*'
    - '(?i).*java.*'
    - '(?i).*jre.*'
    - '(?i).*sdk.*'
    - '(?i).*samples.*'
    - '(?i).*man.*'
    - '(?i).*client.*'
    - '(?i).*gskit.*'
    - '(?i).*amqp.*'
    - '(?i).*ams.*'
    - '(?i).*web.*'
    - '(?i).*(-|_)es.*'
    - '(?i).*(-|_)cn.*'
    # - '(?i).*ftbase.*'
    # - '(?i).*ftlogger.*'
    # - '(?i).*fttools.*'
    # - '(?i).*ftagent.*'
    # - '(?i).*ftservice.*'
    # - '(?i).*xrservice.*'
    # - '(?i).*sfbridge.*'
    # - '(?i).*bcbridge.*'
    # - '(?i).*(-|_)de.*'
    # - '(?i).*(-|_)fr.*'
    # - '(?i).*(-|_)ja.*'
    # - '(?i).*(-|_)it.*'
    # - '(?i).*(-|_)ko.*'
    # - '(?i).*(-|_)ru.*'
    # - '(?i).*(-|_)pt.*'
    # - '(?i).*(-|_)hu.*'
    # - '(?i).*(-|_)pl.*'
    # - '(?i).*(-|_)cs.*'
    # - '(?i).*(-|_)tw.*'
  when:
    - '"MQSeriesRuntime" not in ansible_facts.packages'
    - '"ibmmq-runtime" not in ansible_facts.packages'

- name: Create a list of paths to the packages from found files
  set_fact:
    package_list: "{{ package_files.results | map(attribute='files.0.path') | list }}"
  when: 
    - "'MQSeriesRuntime' not in ansible_facts.packages"
    - "'ibmmq-runtime' not in ansible_facts.packages"

- name: rpm Installation (RedHat)
  dnf:
    name: "{{ package_list }}"
    state: present
    disable_gpg_check: true
  when: 
    - ansible_distribution == 'RedHat'
    - "'MQSeriesRuntime' not in ansible_facts.packages"

- name: rpm Installation (SLES)
  zypper:
    name: "{{ package_list }}"
    state: present
    disable_gpg_check: true
  when: 
    - ansible_distribution == 'SLES'
    - "'MQSeriesRuntime' not in ansible_facts.packages"

- name: deb Installation (Ubuntu)
  apt:
    deb: "{{ item }}"
    state: present
  when: 
    - ansible_distribution == 'Ubuntu'
    - "'ibmmq-runtime' not in ansible_facts.packages"
  with_items:
    - "{{ package_list }}"

- name: reset ssh connection
  meta: reset_connection